---
# Docker role - Install and configure Docker and Docker Compose

- name: Check if Docker is already installed
  command: docker --version
  register: docker_installed
  failed_when: false
  changed_when: false
  tags: [docker]

- name: Install Docker
  block:
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes
  when: docker_installed.rc != 0
  tags: [docker, install]

- name: Add users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ docker_users }}"
  tags: [docker, users]

- name: Configure Docker daemon
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "10m",
          "max-file": "3"
        },
        "storage-driver": "overlay2"
      }
    mode: '0644'
  notify: restart docker
  tags: [docker, config]

- name: Ensure Docker is running
  service:
    name: docker
    state: started
    enabled: yes
  tags: [docker]

- name: Verify Docker Compose is installed
  command: docker compose version
  register: docker_compose_version
  changed_when: false
  tags: [docker]

- name: Display Docker Compose version
  debug:
    msg: "Docker Compose version: {{ docker_compose_version.stdout }}"
  tags: [docker]
